---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

library(tidyverse)

logged_data <- read_csv("stats220 (Responses) - Form responses 1.csv")
glimpse(logged_data)

latest_data <- logged_data %>%
  rename(rally_length = 2,
         server_won_point = 3,
         winning_shot = 4)
```

```{css}
h2 {
  color: #BF77BF;
  font-size: 33px;
  text-decoration: underline;
}

h3 {
  color: #1E90FF;
  font-size: 25px;
}

p {
  font-size: 18px;
}
```

## Analysing Winning Strategies in World-Class Women's Singles Badminton Matches

### Does the server have an advantage in winning points?

```{r}
latest_data %>%
  ggplot() + 
  geom_bar(aes(x = server_won_point, fill = server_won_point)) +
  labs(title = "Number of times server won or lost the point",
       x = "Did the Server Win the Point?",
       y = "Count")
```


```{r}
# maximum value of rally_length
max_rally_length <- latest_data %>% select(rally_length) %>% max

# minimum value of rally_length
min_rally_length <- latest_data %>% select(rally_length) %>% min

# server win rate
server_win_rate <- round(mean(latest_data$server_won_point == "Yes") * 100, 1)
paste("The server won", server_win_rate, "% of rallies, showing",
      ifelse(server_win_rate > 50, "a slight advantage.", "no clear advantage."))
```

### Which shot type is most commonly used to win points?

```{r, fig.width=10, fig.height=6}
latest_data %>%
  ggplot() +
  geom_bar(aes(x = winning_shot, fill = winning_shot)) +
  labs(title = "Number of times each shot type won a point",
       x = "Shot Type",
       y = "Count")
```
